apiKey = "your_api_key_here"
openai_apiKey= "your_openai_api_key_here"

[auth]
redirect_uri = "http://localhost:8501/oauth2callback" # or your deployed URL
cookie_secret = "your_cookie_secret_here"
client_id = "your_client_id_here"
client_secret = "your_client_secret_here"
server_metadata_url = "your_server_metadata_url_here" # if using Google OAuth: https://accounts.google.com/.well-known/openid-configuration